version: '3.9'

services:
  app:
    container_name: ultron-app
    build: 
      context: ./
      dockerfile: ./app/Dockerfile
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: ultron-db
    build: ./db
    environment:
      POSTGRES_USER: wiyseuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: wiyse
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wiyseuser -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5